### PR TITLE
Web interface

### PR DESCRIPTION
**Pull request by guslauer**
The magic can be found in the web-interface folder.

### Run controller on the car
The docker-compose file located in aforementioned folder will run the image with necessary flags to allow access to the controller by first entering the `docker-compose up` to start all the services and then `<cars ip>:5001` in a browser of your liking (Chrome, Firefox and Chromium of latest version has been tested and work well).

### Run/build the controller on your computer
If you, however, want to try the controller locally on your 64/86 and not on the car, just build an image based on Dockerfile.amd64 and run it as follows `docker run --rm -ti --net=host -p 5001:5001 <image name>`. After that, go to the browser and enter `localhost:5001` - voila, you shall see some controllers!

### Lag
Sometimes the controller gets stuck for a second, or two. Stuck in the sense that according to 'Isabelle's animation' the key gets "stuck" thus its release is delayed. Consequently, commands such as stop is a bit delayed which is noticeable when driving the car. It does not, however, happen often, but it is there. It is independent from which platform its ran on, i.e. it does not matter if the controller is ran on the actual car or locally on your computer.

Any ideas? I haven't been able to identify the culprit responsible for the bad behavior so please take a look!

### CODE REVIEW

**Comment by Jeberlen** [comment]
You can approve this! Just fix conflicts!

**Comment by IsabelleTornqvist** [comment]
Same comment as Justas, should .js files really be pushed?
The lag: does it affect the actual manouvering of the car, or just the animation of nav-keys?

**Comment by guslauer** [comment]
Update docker file maintainer

**Comment by guslauer** [comment]
Latest commit; d49c4eabc5da8ea6aa334e1cdf7b26de8337c23d, addresses and fixes the feedback above.

**Pull request merged**
