### PR TITLE
Changed example program to incooperate OD4Session and .odvd message specification for exchanging data

### PR DESCRIPTION
**Pull request by guslauer**
Pull request addresses issue #12 and #15.

### CODE REVIEW

**Comment by Jeberlen** [comment]
I will look into the cmake and travis tonight. Will not approve until the travis build finishes correctly!

**Comment by chrberger** [comment]
Other than my comment above, the changes look fine.

**Comment by Jeberlen** [comment]
Will continue with this tomorrow, after some feedback from Christian.
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/chrberger/libcluon/ubuntu trusty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://ppa.launchpad.net/chrberger/libcluon/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/chrberger/libcluon/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update" failed and exited with 100 during .

**Comment by chrberger** [comment]
We are not providing Ubuntu packages for Ubuntu trusty (14.04) but only for 16.04 and 18.04: https://launchpad.net/~chrberger/+archive/ubuntu/libcluon/+packages

**Pull request merged**
